name: Hello Python Action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Testando o Python
        run: python ../teste.py
      - name: Feedback
        run: echo "Python testado com sucesso!"