name: Test Python App Action

on:
  push:

jobs:
  executar-python:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Executar programa de testes em Python
        run: python test_app.py